/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BAccordionItem: typeof import('bootstrap-vue-next/components/BAccordion')['BAccordionItem']
    BAlert: typeof import('bootstrap-vue-next/components/BAlert')['BAlert']
    BApp: typeof import('bootstrap-vue-next/components/BApp')['BApp']
    BBadge: typeof import('bootstrap-vue-next/components/BBadge')['BBadge']
    BButton: typeof import('./src/components/commons/bootstrap-vue-next/BButton.vue')['default']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BDropdown: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdown']
    BDropdownGroup: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownGroup']
    BDropdownItem: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownItem']
    BDropdownItemButton: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownItemButton']
    BDropdownItemToggle: typeof import('./src/components/commons/tree/BDropdownItemToggle.vue')['default']
    BDropdownText: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownText']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BNavbar: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarBrand']
    BOffcanvas: typeof import('bootstrap-vue-next/components/BOffcanvas')['BOffcanvas']
    BOverlay: typeof import('bootstrap-vue-next/components/BOverlay')['BOverlay']
    BPopover: typeof import('bootstrap-vue-next/components/BPopover')['BPopover']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    BSearchInput: typeof import('./src/components/commons/bootstrap-vue-next/BSearchInput.vue')['default']
    BToast: typeof import('bootstrap-vue-next/components/BToast')['BToast']
    ClampText: typeof import('./src/components/commons/ClampText.vue')['default']
    copy: typeof import('./src/components/commons/tree/TreeItem copy.vue')['default']
    DateRangePicker: typeof import('./src/components/commons/DateRangePicker.vue')['default']
    FileIcon: typeof import('./src/components/commons/FileIcon.vue')['default']
    ItemToggle: typeof import('./src/components/commons/tree/ItemToggle.vue')['default']
    MonthPicker: typeof import('./src/components/commons/MonthPicker.vue')['default']
    RootTree: typeof import('./src/components/commons/tree/RootTree.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TreeItem: typeof import('./src/components/commons/tree/TreeItem.vue')['default']
    TreeItemToggle: typeof import('./src/components/commons/tree/TreeItemToggle.vue')['default']
    TreeNode: typeof import('./src/components/commons/tree/TreeNode.vue')['default']
    UIcon: typeof import('./src/components/commons/unplugin-icons/UIcon.vue')['default']
  }
  export interface GlobalDirectives {
    vBToggle: typeof import('bootstrap-vue-next/directives/BToggle')['vBToggle']
  }
}
