/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BAccordionItem: typeof import('bootstrap-vue-next/components/BAccordion')['BAccordionItem']
    BAlert: typeof import('bootstrap-vue-next/components/BAlert')['BAlert']
    BApp: typeof import('bootstrap-vue-next/components/BApp')['BApp']
    BButton: typeof import('./src/components/commons/bootstrap-vue-next/BButton.vue')['default']
    BDropdown: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdown']
    BDropdownItem: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownItem']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BOverlay: typeof import('bootstrap-vue-next/components/BOverlay')['BOverlay']
    BPopover: typeof import('bootstrap-vue-next/components/BPopover')['BPopover']
    BSearchInput: typeof import('./src/components/commons/bootstrap-vue-next/BSearchInput.vue')['default']
    BToast: typeof import('bootstrap-vue-next/components/BToast')['BToast']
    ClampText: typeof import('./src/components/commons/ClampText.vue')['default']
    DateRangePicker: typeof import('./src/components/commons/DateRangePicker.vue')['default']
    FileIcon: typeof import('./src/components/commons/FileIcon.vue')['default']
    MonthPicker: typeof import('./src/components/commons/MonthPicker.vue')['default']
    RootTree: typeof import('./src/components/commons/tree/RootTree.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TreeItem: typeof import('./src/components/commons/tree/TreeItem.vue')['default']
    TreeNode: typeof import('./src/components/commons/tree/TreeNode.vue')['default']
    UIcon: typeof import('./src/components/commons/unplugin-icons/UIcon.vue')['default']
  }
}
